services:
  - type: web
    name: flower-detection-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        sync: false
